### ISSUE TITLE
二维码过期了, 顺便问个异步相关的问题

### ISSUE THREAD

**Issue by YeFei572** [draftbk/flutter_road#3]
作者, 你二维码过期了..

另外dart语言是单线程模型, 任何任务加载执行都在一个线程上, 在此基础上, 我想问一下, 所有的网络图片加载是异步的吗? 从哪儿可以看出来他是异步的?

**Comment by draftbk** [comment]
谢谢提醒，现在已经更新了。

关于异步，dart 语言的确是单线程模型，不过在我的理解里异步和多线程是不完全一样的，在我们执行某个任务 A 后，我们不需要马上得到结果，可以先执行它之后的任务 BC，然后当 A 执行完成以后再回调，这样应该算是异步。在我学习笔记 [Flutter 学习之路 - 异步任务](https://github.com/draftbk/flutter_road/blob/master/notes/Flutter_Async.md)里面最后那个部分有提到，就是 task2 没有执行完但是不影响 task3, task4 的执行，可以看出 flutter 的异步。
（仅供参考，希望有帮助(´・ω・`)）

**Comment by YeFei572** [comment]
先谢谢作者回复!

是这样, 我现在有一个页面, 页面上涉及了 三个接口请求, 而布局我则使用的是`CustomScrollView`包裹三个`SliverToBoxAdapter`, 每个`SliverToBoxAdapter`里面放一个`FutureBuilder`, 如此我的页面完成布局, 下拉刷新后显得很卡, 我在想当页面刷新的时候这三个接口是异步调用吗? 因为三个接口返回的都是图片, 而且我布局里面都是图片, 所以我这边日志经常说主线程太忙, 跳过多少个工作.. 然后打包成了release的时候就闪退, 
我的接口没有问题, 页面也没有报错, 所以很纠结, 不知道作者有没有解决方案.

**Comment by draftbk** [comment]
@YeFei572 我也还是在学习中，也没有解决过这类的问题，你可以在咱们群里问问看，之后如果有解决方案还请贴过来呀

**Comment by YeFei572** [comment]
好吧, 如果得到解决我会贴上来的
